export enum Platform {
  NAVER = 'naver',
  DAUM = 'daum',
  KAKAO = 'kakao',
  LEZIN = 'lezin',
  TOOMICS = 'toomics',
  TOPTOON = 'toptoon',
  MISTERBLUE = 'misterblue',
}

export enum Weekday {
  MON = 'mon',
  TUE = 'tue',
  WED = 'wed',
  THU = 'thu',
  FRI = 'fri',
  SAT = 'sat',
  SUN = 'sun',
  TEN = 'ten',
  월 = 'mon',
  화 = 'tue',
  수 = 'wed',
  목 = 'thu',
  금 = 'fri',
  토 = 'sat',
  일 = 'sun',
  열흘 = 'ten',
  mon = '1',
  tue = '2',
  wed = '3',
  thu = '4',
  fri = '5',
  sat = '6',
  sun = '7',
}

export enum Genre {
  EPISODE = '에피소드',
  OMNIBUS = '옴니버스',
  STORY = '스토리',
  HORROR = '호러',
  DRAMA = '드라마',
  SF = 'SF',
  HISTORICAL = '시대극',
  MYSTERY = '미스테리',
  ROMANCE = '순정',
  THRILLER = '스릴러',
  SPORTS = '스포츠',
  ACTION = '액션',
  DAILY = '일상',
  FOOD = '음식',
  KNOWLEDGE = '지식',
  GAG = '개그',
  FANTASY = '판타지',
  ACADEMY = '학원',
  ADULT = '성인',
  BL = 'BL',
  GL = 'GL',
}
